name: Web-Release

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - uses: actions/checkout@v3
      - name: Web Build
        working-directory: ./headless_haystack
        run: |
          flutter build web --release --base-href "/headless-haystack/"
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./headless_haystack/build/web