name: Web and Android-Release

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - uses: actions/checkout@v3
      - name: Android Build
        working-directory: ./headless_haystack
        run: |
          flutter pub get
          flutter build apk --release
      - name: Rename Apk
        run: mv ./headless_haystack/build/app/outputs/flutter-apk/app-release.apk ./headless_haystack/build/app/outputs/flutter-apk/android-application.apk
      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-application
          path: ./headless_haystack/build/app/outputs/flutter-apk/android-application.apk
      - name: Web Build
        working-directory: ./headless_haystack
        run: |
          flutter build web --release
      - name: Copy files to web application
        run: |
          mkdir -p ./headless_haystack/build/webapplication
          cp ./webserver/FindMy_proxy.py ./headless_haystack/build/webapplication
          cp ./webserver/apple_cryptography.py  ./headless_haystack/build/webapplication
          cp -R ./headless_haystack/build/web ./headless_haystack/build/webapplication
      - name: Upload Web Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-webapplication
          path: ./headless_haystack/build/webapplication
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./headless_haystack/build/web